### ISSUE TITLE
Error occurs when running the example "data-frame.jl"

### ISSUE THREAD

**Issue by nsapy** [jverzani/PySide.jl#11]
julia> include("data-frame.jl");
ERROR: `TableView` has no method matching TableView()
 in include at
 in include_from_node1 at  (repeats 3 times)
while loading \home\pc\data-frame.jl, in expression starting on line 12

**Comment by jverzani** [comment]
Thanks. I had disabled the code to make that example run (at the time) as `DataFrames.jl` took too long to load. I just checked in a fix for that using `Requires.jl`. As well, I had to clean up some of the data frames code to reflect changes since this codebase was last touched. (Which has been quite awhile.) Now the example works for me. If not for you, please let me know.

**Comment by nsapy** [comment]
I ran the modified example again, I can see the popup window but the cells in the table are all empty and in the console the error message turned out to be:
...
TypeError: an integer is required
TypeError: an integer is required
TypeError: an integer is required
TypeError: an integer is required
TypeError: an integer is required
TypeError: an integer is required
...

**Comment by jverzani** [comment]
Very odd, can you forward on any details as to your version of OS, Julia, PySide, Qt, ... I can't repeat this on my mac, but perhaps their is some lurking issue that can be addressed.
